# Generated by Django 2.0.13 on 2019-11-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128)),
                ('referrer', models.CharField(blank=True, max_length=512)),
                ('username', models.CharField(blank=True, max_length=256)),
                ('method', models.CharField(max_length=16)),
                ('path', models.CharField(max_length=128)),
                ('data', models.TextField(blank=True)),
                ('response_status', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('highlight', models.CharField(max_length=128)),
            ],
        ),
    ]
