version: 0.0
os: linux
files:
 - source: /apps/
   destination: /home/ubuntu/apps
 - source: /files/
   destination: /home/ubuntu/files
 - source: /requirements/
   destination: /home/ubuntu/requirements
 - source: /supervisord.conf
   destination: /home/ubuntu

permissions:
  - object: /home/ubuntu/apps/manage.py
    owner: ubuntu
    mode: 644
    type:
      - file
  - object: /home/ubuntu/supervisord.conf
    owner: ubuntu
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu
