version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/siss
 - source: /nginx-siss.conf
   destination: /etc/nginx/conf.d

permissions:
  - object: /home/ubuntu/siss
    owner: root
    group: root
    mode: 755
      
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root