version: 0.0
os: linux
files:
 - source: /apps/
   destination: /home/ec2-user/apps
 - source: /files/
   destination: /home/ec2-user/files
 - source: /requirements/
   destination: /home/ec2-user/requirements
 - source: /supervisord.conf
   destination: /home/ec2-user

permissions:
  - object: /home/ec2-user/
    owner: ubuntu
    mode: 644
    type:
      - directory
      
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root