version: 0.0
os: linux
files:
 - source: /apps/
   destination: /home/ec2-user/apps
 - source: /files/
   destination: /home/ec2-user/files
 - source: /requirements/
   destination: /home/ec2-user/requirements
 - source: /supervisord.conf
   destination: /home/ec2-user

permissions:
  - object: /home/ec2-user/apps/manage.py
    owner: root
    mode: 644
    type:
      - file
  - object: /home/ec2-user/supervisord.conf
    owner: root
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root