version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user

permissions:
  - object: /home/ec2-user
    owner: ubuntu
    group: ubuntu
    mode: 644
      
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu