version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/siss
    
permissions:
  - object: /home/ubuntu/siss
    owner: ubuntu
    group: ubuntu
    mode: 777

hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu
