# Generated by Django 2.0.13 on 2019-09-30 16:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KualiEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=256, null=True)),
                ('tracking_id', models.CharField(max_length=256, null=True)),
                ('fullname_kuali', models.CharField(max_length=256, null=True)),
                ('siss_account', models.CharField(max_length=256, null=True)),
                ('dept_account', models.CharField(max_length=256, null=True)),
                ('amount_kuali', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=128)),
                ('date_kuali', models.DateField(null=True)),
                ('ref_id', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SunapsisEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunapsis_id', models.CharField(max_length=256, null=True)),
                ('firstname_sunapsis', models.CharField(max_length=256, null=True)),
                ('lastname_sunapsis', models.CharField(max_length=256, null=True)),
                ('job_title_sunapsis', models.CharField(max_length=256, null=True)),
                ('position', models.IntegerField()),
                ('dept_name_sunapsis', models.CharField(max_length=256, null=True)),
                ('visa_amount_sunapsis', models.CharField(max_length=256, null=True)),
                ('visa_sunapsis', models.CharField(max_length=256, null=True)),
                ('amount_sunapsis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=128)),
                ('date_sunapsis', models.DateField(null=True)),
                ('ref_id', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
