# Generated by Django 2.0.13 on 2019-09-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kualientry',
            name='firstname_kuali',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='kualientry',
            name='lastname_kuali',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='kualientry',
            name='ref_sunapsis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.SunapsisEntry'),
        ),
        migrations.AddField(
            model_name='sunapsisentry',
            name='doc_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sunapsisentry',
            name='fullname_sunapsis',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sunapsisentry',
            name='ref_kuali',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.KualiEntry'),
        ),
    ]
