# Generated by Django 2.0.13 on 2019-10-07 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20190930_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sunapsisentry',
            old_name='position',
            new_name='position_id_sunapsis',
        ),
        migrations.AddField(
            model_name='sunapsisentry',
            name='dept_contact_sunapsis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='date_kuali',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='dept_account',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='doc_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='firstname_kuali',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='fullname_kuali',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='lastname_kuali',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='ref_sunapsis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.SunapsisEntry'),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='siss_account',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kualientry',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='date_sunapsis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='dept_name_sunapsis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='doc_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='firstname_sunapsis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='fullname_sunapsis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='job_title_sunapsis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='lastname_sunapsis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='ref_kuali',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.KualiEntry'),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='sunapsis_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='visa_amount_sunapsis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='visa_sunapsis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
