# Generated by Django 2.0.13 on 2019-10-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_auto_20191006_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunapsisentry',
            name='amount_sunapsis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=128, null=True),
        ),
        migrations.AlterField(
            model_name='sunapsisentry',
            name='position_id_sunapsis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
