#!/bin/bash
add-apt-repository ppa:jonathonf/python-3.6 -y
apt-get update
apt-get install python3.6 ruby wget -y
cd /home/ubuntu
wget https://aws-codedeploy-us-east-2.s3.us-east-2.amazonaws.com/latest/install
chmod +x ./install
./install auto
service codedeploy-agent start