#!/bin/bash

apt-get update
apt-get install python3 python3-pip nginx -y
pip3 install virtualenv supervisor

cd /home/ubuntu/siss
virtualenv environment -p python3.6
source environment/bin/activate
pip install -r requirements/prod.txt