#!/bin/bash

apt-get update
apt-get install python3 python3-pip -y
pip3 install virtualenv supervisor

cd /home/ubuntu/siss
virtualenv environment
source environment/bin/activate
pip install -r requirements/prod.txt