# Generated by Django 2.0.13 on 2019-11-06 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KualiEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(blank=True, max_length=256, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=256, null=True)),
                ('fullname_kuali', models.CharField(blank=True, max_length=256, null=True)),
                ('firstname_kuali', models.CharField(blank=True, max_length=256, null=True)),
                ('lastname_kuali', models.CharField(blank=True, max_length=256, null=True)),
                ('siss_account', models.CharField(blank=True, max_length=256, null=True)),
                ('dept_account', models.CharField(blank=True, max_length=256, null=True)),
                ('amount_kuali', models.DecimalField(blank=True, decimal_places=2, max_digits=128, null=True)),
                ('date_kuali', models.DateField(blank=True, null=True)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SunapsisEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(blank=True, max_length=256, null=True)),
                ('sunapsis_id', models.CharField(blank=True, max_length=256, null=True)),
                ('fullname_sunapsis', models.CharField(blank=True, max_length=256, null=True)),
                ('firstname_sunapsis', models.CharField(blank=True, max_length=256, null=True)),
                ('lastname_sunapsis', models.CharField(blank=True, max_length=256, null=True)),
                ('job_title_sunapsis', models.CharField(blank=True, max_length=256, null=True)),
                ('position_id_sunapsis', models.IntegerField(blank=True, null=True)),
                ('dept_name_sunapsis', models.CharField(blank=True, max_length=256, null=True)),
                ('dept_contact_sunapsis', models.CharField(blank=True, max_length=256, null=True)),
                ('visa_amount_sunapsis', models.CharField(blank=True, max_length=256, null=True)),
                ('visa_sunapsis', models.CharField(blank=True, max_length=256, null=True)),
                ('amount_sunapsis', models.DecimalField(blank=True, decimal_places=2, max_digits=128, null=True)),
                ('date_sunapsis', models.DateField(blank=True, null=True)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('ref_kuali', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.KualiEntry')),
            ],
        ),
        migrations.AddField(
            model_name='kualientry',
            name='ref_sunapsis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.SunapsisEntry'),
        ),
    ]
